name: "automerge"

permissions:
  pull-requests: write
  contents: write

on:
  pull_request_target:
    types:
      - "labeled"
  check_suite:
    types:
      - "completed"
  status: {}
jobs:
  approve:
    uses: "./.github/workflows/auto-approve.yml"

    if: ${{ github.actor == 'dependabot[bot]' }}

    with:
      pullRequestNumber: "${{ github.event.pull_request.number }}"
    secrets:
      envPAT: "${{ secrets.GITHUB_TOKEN }}"
  automerge:
    needs: "approve"

    uses: "./.github/workflows/auto-merge.yml"

    with:
      pullRequestNumber: "${{ github.event.pull_request.number }}"
    secrets:
      envPAT: "${{ secrets.GITHUB_TOKEN }}"
