name: "automerge"

permissions:
  pull-requests: write
  contents: write

on: pull_request_target

jobs:
  approve:
    uses: "./.github/workflows/auto-approve.yml"

    if: ${{ github.actor == 'dependabot[bot]' }}

    with:
      pullRequestNumber: "${{ github.event.pull_request.number }}"
    secrets:
      envPAT: "${{ secrets.GITHUB_TOKEN }}"
  automerge:
    needs: "approve"

    uses: "./.github/workflows/auto-merge.yml"

    secrets:
      envPAT: "${{ secrets.GITHUB_TOKEN }}"
  test:
    name: "Test"

    runs-on: "ubuntu-22.04"
    timeout-minutes: 10
    continue-on-error: false

    steps:
      - name: "print something about github info"
        run: "echo 'env: ${{ github.env }} event: ${{ github.event_name }} repo: {{ github.repository }} workflow-ref: ${{ github.workflow }}-${{ github.ref }}'"
