name: "Auto merge"

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
    inputs:
      pullRequestUrl:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  automerge:
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Dependabot metadata"
        id: "metadata"

        uses: "dependabot/fetch-metadata@v1.3.5"

        with:
          github-token: ${{ secrets.envPAT }}

      - name: "Enable auto-merge for Dependabot PRs"
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}

        run: gh pr merge --auto --merge "$PR_URL"

        env:
          PR_URL: "${{ inputs.pullRequestUrl }}"
          GITHUB_TOKEN: ${{ secrets.envPAT }}
