name: "Auto approve"

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
    inputs:
      pullRequestUrl:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  auto-approve:
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Dependabot metadata"
        id: "metadata"

        uses: "dependabot/fetch-metadata@v1.3.6"

        with:
          github-token: ${{ secrets.envPAT }}

      - name: "Approve patch and minor updates"
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}

        run: gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"

        env:
          PR_URL: "${{ inputs.pullRequestUrl }}"
          GITHUB_TOKEN: ${{ secrets.envPAT }}
