name: "Auto approve"

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
    inputs:
      pullRequestUrl:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  auto-approve:
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Dependabot metadata"
        id: "metadata"

        uses: "dependabot/fetch-metadata@v1.3.6"

        with:
          github-token: ${{ secrets.envPAT }}

      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "print update-type"

        run: echo ${{ steps.metadata.outputs.update-type }}

      - name: "Approve patch and minor updates"
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}

        run: |
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review "$PR_URL" --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi

        env:
          PR_URL: "${{ inputs.pullRequestUrl }}"
          GITHUB_TOKEN: ${{ secrets.envPAT }}
