# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: "Continuous Integration"

env:
  PHP_EXTENSIONS: "json, opcache"
  PHP_INI_VALUES: "opcache.enable=1, opcache.enable_cli=1, zend.assertions=1, assert.exception=On"

jobs:
  validate:
    name: "Validate composer"

    runs-on: "${{ matrix.operating-system }}"

    continue-on-error: false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

        php-version:
          - "7.4"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          coverage: "none"
          tools: "composer:v2, composer-normalize"

      - name: "Validate composer.json"
        run: "composer validate --strict"

      - name: "Run composer-normalize"
        run: "composer-normalize --dry-run"

  install:
    name: "Check dependencies"

    needs: "validate"

    runs-on: "${{ matrix.operating-system }}"

    continue-on-error: ${{ matrix.continue-on-error }}

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"

        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

        dependencies:
          - "--prefer-lowest"
          - ""

        continue-on-error:
          - false

        include:
          - operating-system: "ubuntu-latest"
            php-version: "8.1"
            dependencies: "--prefer-lowest"
            continue-on-error: true
          - operating-system: "ubuntu-latest"
            php-version: "8.1"
            dependencies: ""
            continue-on-error: true
          - operating-system: "windows-latest"
            dependencies: "--prefer-lowest"
            php-version: "8.1"
            continue-on-error: true
          - operating-system: "windows-latest"
            dependencies: ""
            php-version: "8.1"
            continue-on-error: true
          - operating-system: "macos-latest"
            dependencies: "--prefer-lowest"
            php-version: "8.1"
            continue-on-error: true
          - operating-system: "macos-latest"
            dependencies: ""
            php-version: "8.1"
            continue-on-error: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          coverage: "none"
          tools: "composer:v2"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv ${{ matrix.dependencies }}"

      - name: "Check dependencies with composer"
        run: "composer outdated --direct --strict"

  php-cs-fixer:
    name: "Check Coding Standards with PHP-CS-Fixer"

    needs: "install"

    runs-on: "${{ matrix.operating-system }}"

    continue-on-error: false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

        php-version:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          coverage: "none"
          tools: "composer:v2"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv ${{ matrix.dependencies }}"

      - name: "Run friendsofphp/php-cs-fixer"
        run: "vendor/bin/php-cs-fixer fix --dry-run -vv"

  phpcs:
    name: "Check Coding Standards with PHPCS"

    needs: "install"

    runs-on: "${{ matrix.operating-system }}"

    continue-on-error: false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

        php-version:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          coverage: "none"
          tools: "composer:v2"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv ${{ matrix.dependencies }}"

      - name: "Run squizlabs/php_codesniffer"
        uses: "chekalsky/phpcs-action@v1.2.0"
        with:
          phpcs_bin_path: "./vendor/bin/phpcs"
          enable_warnings: true

  static-code-analysis:
    name: "Static Code Analysis with PHPStan"

    needs: "install"

    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

        php-version:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          coverage: "none"
          tools: "composer:v2"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv ${{ matrix.dependencies }}"

      - name: "Run phpstan/phpstan"
        run: "vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=768M --no-progress"

  tests:
    name: "UnitTests with PHPUnit"

    needs: "install"

    runs-on: "${{ matrix.operating-system }}"

    continue-on-error: ${{ matrix.continue-on-error }}

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"

        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"

        dependencies:
          - ""

        continue-on-error:
          - false

        include:
          - operating-system: "ubuntu-latest"
            php-version: "8.0"
            continue-on-error: true
          - operating-system: "windows-latest"
            php-version: "8.0"
            continue-on-error: true
          - operating-system: "macos-latest"
            php-version: "8.0"
            continue-on-error: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          coverage: "none"
          tools: "composer:v2"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv ${{ matrix.dependencies }}"

      - name: "Run unit tests with phpunit/phpunit"
        run: "vendor/bin/phpunit -c phpunit.xml --colors --no-coverage"

  code-coverage:
    name: "Code Coverage"

    needs: "tests"

    runs-on: "${{ matrix.operating-system }}"

    continue-on-error: false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

        php-version:
          - "7.1"

        dependencies:
          - ""

        coverage-drivers:
          - "xdebug"
          - "pcov"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          coverage: "${{ matrix.coverage-drivers }}"
          tools: "composer:v2"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv ${{ matrix.dependencies }}"

      - name: "Create cache directory for phpunit/phpunit"
        run: "mkdir -p .build/coverage"

      #- name: "Collect code coverage with Xdebug and phpunit/phpunit"
      #  run: "vendor/bin/phpunit -c phpunit.xml --colors --coverage-clover=.build/coverage/clover.xml --coverage-text --coverage-xml=.build/coverage/coverage-xml --log-junit=.build/coverage/phpunit.junit.xml"

      #- name: "Upload coverage to Codecov"
      #  uses: "codecov/codecov-action@v1.0.14"
      #  with:
      #    token: "${{secrets.CODECOV_TOKEN}}"
      #    file: ".build/coverage/clover.xml"
      #    flags: "phpunit"

      #- name: "Run mutation tests with infection/infection"
      #  run: "vendor/bin/infection --min-covered-msi=95 --min-msi=95 --coverage=.build/coverage"
